//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNutrideal_desktop.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Refeicao", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceNutrideal")]
    [System.SerializableAttribute()]
    public partial class Refeicao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaloriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestauranteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calorias {
            get {
                return this.CaloriasField;
            }
            set {
                if ((object.ReferenceEquals(this.CaloriasField, value) != true)) {
                    this.CaloriasField = value;
                    this.RaisePropertyChanged("Calorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantidadeField, value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restaurante {
            get {
                return this.RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.RestauranteField, value) != true)) {
                    this.RestauranteField = value;
                    this.RaisePropertyChanged("Restaurante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicao", ReplyAction="http://tempuri.org/IService/GetRefeicaoResponse")]
        eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicao", ReplyAction="http://tempuri.org/IService/GetRefeicaoResponse")]
        System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicaoPorRestaurante", ReplyAction="http://tempuri.org/IService/GetRefeicaoPorRestauranteResponse")]
        eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicaoPorRestaurante(string restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicaoPorRestaurante", ReplyAction="http://tempuri.org/IService/GetRefeicaoPorRestauranteResponse")]
        System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoPorRestauranteAsync(string restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicaoPorItem", ReplyAction="http://tempuri.org/IService/GetRefeicaoPorItemResponse")]
        eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicaoPorItem(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRefeicaoPorItem", ReplyAction="http://tempuri.org/IService/GetRefeicaoPorItemResponse")]
        System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoPorItemAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRefeicao", ReplyAction="http://tempuri.org/IService/AddRefeicaoResponse")]
        void AddRefeicao(eNutrideal_desktop.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRefeicao", ReplyAction="http://tempuri.org/IService/AddRefeicaoResponse")]
        System.Threading.Tasks.Task AddRefeicaoAsync(eNutrideal_desktop.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addListRefeicoesToXML", ReplyAction="http://tempuri.org/IService/addListRefeicoesToXMLResponse")]
        void addListRefeicoesToXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addListRefeicoesToXML", ReplyAction="http://tempuri.org/IService/addListRefeicoesToXMLResponse")]
        System.Threading.Tasks.Task addListRefeicoesToXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/recebeRefeicao", ReplyAction="http://tempuri.org/IService/recebeRefeicaoResponse")]
        void recebeRefeicao(eNutrideal_desktop.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/recebeRefeicao", ReplyAction="http://tempuri.org/IService/recebeRefeicaoResponse")]
        System.Threading.Tasks.Task recebeRefeicaoAsync(eNutrideal_desktop.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CriaXML", ReplyAction="http://tempuri.org/IService/CriaXMLResponse")]
        void CriaXML(string restaurante, string item, string quantidade, string calorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CriaXML", ReplyAction="http://tempuri.org/IService/CriaXMLResponse")]
        System.Threading.Tasks.Task CriaXMLAsync(string restaurante, string item, string quantidade, string calorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ApagarRefeicaoPorItem", ReplyAction="http://tempuri.org/IService/ApagarRefeicaoPorItemResponse")]
        void ApagarRefeicaoPorItem(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ApagarRefeicaoPorItem", ReplyAction="http://tempuri.org/IService/ApagarRefeicaoPorItemResponse")]
        System.Threading.Tasks.Task ApagarRefeicaoPorItemAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularPesoIdeal", ReplyAction="http://tempuri.org/IService/CalcularPesoIdealResponse")]
        double CalcularPesoIdeal(int idade, int altura, string genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularPesoIdeal", ReplyAction="http://tempuri.org/IService/CalcularPesoIdealResponse")]
        System.Threading.Tasks.Task<double> CalcularPesoIdealAsync(int idade, int altura, string genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularCaloriasDia", ReplyAction="http://tempuri.org/IService/CalcularCaloriasDiaResponse")]
        double CalcularCaloriasDia(int idade, string genero, int altura, double peso, string nivelAtividade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularCaloriasDia", ReplyAction="http://tempuri.org/IService/CalcularCaloriasDiaResponse")]
        System.Threading.Tasks.Task<double> CalcularCaloriasDiaAsync(int idade, string genero, int altura, double peso, string nivelAtividade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularPlanoCalorico", ReplyAction="http://tempuri.org/IService/CalcularPlanoCaloricoResponse")]
        string CalcularPlanoCalorico(double peso, double pesoIdeal, double caloriasDiaParaManter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcularPlanoCalorico", ReplyAction="http://tempuri.org/IService/CalcularPlanoCaloricoResponse")]
        System.Threading.Tasks.Task<string> CalcularPlanoCaloricoAsync(double peso, double pesoIdeal, double caloriasDiaParaManter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : eNutrideal_desktop.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<eNutrideal_desktop.ServiceReference1.IService>, eNutrideal_desktop.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicao() {
            return base.Channel.GetRefeicao();
        }
        
        public System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoAsync() {
            return base.Channel.GetRefeicaoAsync();
        }
        
        public eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicaoPorRestaurante(string restaurante) {
            return base.Channel.GetRefeicaoPorRestaurante(restaurante);
        }
        
        public System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoPorRestauranteAsync(string restaurante) {
            return base.Channel.GetRefeicaoPorRestauranteAsync(restaurante);
        }
        
        public eNutrideal_desktop.ServiceReference1.Refeicao[] GetRefeicaoPorItem(string item) {
            return base.Channel.GetRefeicaoPorItem(item);
        }
        
        public System.Threading.Tasks.Task<eNutrideal_desktop.ServiceReference1.Refeicao[]> GetRefeicaoPorItemAsync(string item) {
            return base.Channel.GetRefeicaoPorItemAsync(item);
        }
        
        public void AddRefeicao(eNutrideal_desktop.ServiceReference1.Refeicao refeicao) {
            base.Channel.AddRefeicao(refeicao);
        }
        
        public System.Threading.Tasks.Task AddRefeicaoAsync(eNutrideal_desktop.ServiceReference1.Refeicao refeicao) {
            return base.Channel.AddRefeicaoAsync(refeicao);
        }
        
        public void addListRefeicoesToXML() {
            base.Channel.addListRefeicoesToXML();
        }
        
        public System.Threading.Tasks.Task addListRefeicoesToXMLAsync() {
            return base.Channel.addListRefeicoesToXMLAsync();
        }
        
        public void recebeRefeicao(eNutrideal_desktop.ServiceReference1.Refeicao refeicao) {
            base.Channel.recebeRefeicao(refeicao);
        }
        
        public System.Threading.Tasks.Task recebeRefeicaoAsync(eNutrideal_desktop.ServiceReference1.Refeicao refeicao) {
            return base.Channel.recebeRefeicaoAsync(refeicao);
        }
        
        public void CriaXML(string restaurante, string item, string quantidade, string calorias) {
            base.Channel.CriaXML(restaurante, item, quantidade, calorias);
        }
        
        public System.Threading.Tasks.Task CriaXMLAsync(string restaurante, string item, string quantidade, string calorias) {
            return base.Channel.CriaXMLAsync(restaurante, item, quantidade, calorias);
        }
        
        public void ApagarRefeicaoPorItem(string item) {
            base.Channel.ApagarRefeicaoPorItem(item);
        }
        
        public System.Threading.Tasks.Task ApagarRefeicaoPorItemAsync(string item) {
            return base.Channel.ApagarRefeicaoPorItemAsync(item);
        }
        
        public double CalcularPesoIdeal(int idade, int altura, string genero) {
            return base.Channel.CalcularPesoIdeal(idade, altura, genero);
        }
        
        public System.Threading.Tasks.Task<double> CalcularPesoIdealAsync(int idade, int altura, string genero) {
            return base.Channel.CalcularPesoIdealAsync(idade, altura, genero);
        }
        
        public double CalcularCaloriasDia(int idade, string genero, int altura, double peso, string nivelAtividade) {
            return base.Channel.CalcularCaloriasDia(idade, genero, altura, peso, nivelAtividade);
        }
        
        public System.Threading.Tasks.Task<double> CalcularCaloriasDiaAsync(int idade, string genero, int altura, double peso, string nivelAtividade) {
            return base.Channel.CalcularCaloriasDiaAsync(idade, genero, altura, peso, nivelAtividade);
        }
        
        public string CalcularPlanoCalorico(double peso, double pesoIdeal, double caloriasDiaParaManter) {
            return base.Channel.CalcularPlanoCalorico(peso, pesoIdeal, caloriasDiaParaManter);
        }
        
        public System.Threading.Tasks.Task<string> CalcularPlanoCaloricoAsync(double peso, double pesoIdeal, double caloriasDiaParaManter) {
            return base.Channel.CalcularPlanoCaloricoAsync(peso, pesoIdeal, caloriasDiaParaManter);
        }
    }
}
